"""Pydantic schemas for QBR Intelligence."""

from qbr_intelligence.schemas.documents import (
    ChartCreate,
    ChartRead,
    ChunkCreate,
    ChunkRead,
    DocumentCreate,
    DocumentRead,
    DocumentSummary,
    EntityCreate,
    EntityRead,
    ImageCreate,
    ImageRead,
    MetricCreate,
    MetricRead,
    SectionCreate,
    SectionRead,
    SlideCreate,
    SlideRead,
)
from qbr_intelligence.schemas.llm_outputs import (
    ChartReconstructionOutput,
    EntityExtractionOutput,
    ExecutiveSummaryOutput,
    ExtractedEntity,
    ExtractedMetric,
    MetricDeduplicationOutput,
    MetricNormalizationOutput,
    MetricRefinementOutput,
    RefinedMetric,
    SlideAnalysisOutput,
)
from qbr_intelligence.schemas.queries import (
    DocumentFilter,
    FacetFilter,
    MetricFilter,
    QueryRequest,
    QueryResponse,
    SearchResult,
)

__all__ = [
    # Documents
    "DocumentCreate",
    "DocumentRead",
    "DocumentSummary",
    "SectionCreate",
    "SectionRead",
    "SlideCreate",
    "SlideRead",
    "MetricCreate",
    "MetricRead",
    "ChartCreate",
    "ChartRead",
    "ImageCreate",
    "ImageRead",
    "EntityCreate",
    "EntityRead",
    "ChunkCreate",
    "ChunkRead",
    # LLM Outputs
    "SlideAnalysisOutput",
    "MetricDeduplicationOutput",
    "MetricNormalizationOutput",
    "MetricRefinementOutput",
    "RefinedMetric",
    "ExtractedMetric",
    "ChartReconstructionOutput",
    "ExecutiveSummaryOutput",
    "EntityExtractionOutput",
    "ExtractedEntity",
    # Queries
    "QueryRequest",
    "QueryResponse",
    "SearchResult",
    "DocumentFilter",
    "MetricFilter",
    "FacetFilter",
]
